version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty12345
  app:
    build: .
    # DEBUG
#    volumes:
#     - .:/opt/app
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
